apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvaalenetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvaalepod
  template:
    metadata:
      labels:
        app: kvaalepod
    spec:
      containers:
        - name: kvaaleteiner
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 50Mi
          image: wkvaale/python-flask
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: kvaaleservice
spec:
  selector:
    app: kvaalepod
  ports:
    - protocol: TCP
      port: 5000
